[workspace]

[package]
name = "flm-scripts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "align_versions"
path = "align_versions.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

